name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Cache Flutter SDK
      uses: actions/cache@v2
      with:
        path: ~/.flutter
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-flutter-

    - name: Install Flutter SDK
      run: |
        git clone https://github.com/flutter/flutter.git -b stable
        export PATH="$PATH:`pwd`/flutter/bin"
        flutter precache

    - name: Install Flutter dependencies
      run: flutter pub get

    - name: Run Flutter tests
      run: flutter test
